add refund bid functions
Polygon-Fast-Lane/auction pull request #9
Opened 2023-05-26 03:34 UTC by Code0x2

adds the `submitFlashBidWithRefund` and `updateValidatorRefundShare` functions for orderflow protocols to receive refunds of the bid

2023-05-30 15:59 UTC, Elyx0 requested changes

2023-05-31 00:56 UTC, Code0x2 commented on contracts/auction-handler/FastLaneAuctionHandler.sol
> +        validatorsRefundShareMap[validator] = refundShare;
validators can set above the limit if they want to, they just wont get sent any bundles from the sentry

2023-07-07 06:37 UTC, Elyx0 commented on contracts/auction-handler/FastLaneAuctionHandler.sol
> +    error RelayValidatorNotAcceptingRefundBids();
Pleas comment with the selector ( cast sig "RelayValidatorNotAcceptingRefundBids()" )

2023-07-07 06:38 UTC, Elyx0 commented on contracts/auction-handler/FastLaneAuctionHandler.sol
> +    error RelayAuctionInvalidBid();
Pleas comment with the selector ( cast sig "RelayAuctionInvalidBid()" )

2023-07-07 06:49 UTC, Elyx0 approved these changes

2023-07-08 03:35 UTC, merged